# Generated by Django 5.0.7 on 2024-08-03 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("thumb", models.ImageField(upload_to="thumbs_filmes/")),
                ("descricao", models.TextField(max_length=1000)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("visualizacoes", models.IntegerField(default=0)),
            ],
        ),
    ]
