# Generated by Django 5.0.7 on 2024-08-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("a", "selecione uma categoria"),
                    ("acao", "Ação"),
                    ("comedia", "Comédia"),
                    ("drama", "Drama"),
                    ("romance", "Romance"),
                    ("suspense", "Suspense"),
                    ("terror", "Terror"),
                    ("ficcao", "Ficção Científica"),
                ],
                default="drama",
                max_length=20,
            ),
        ),
    ]
